"""Initial migration.

Revision ID: 857c77a9eab0
Revises: fd7868b5c3bc
Create Date: 2022-11-24 12:58:11.809928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '857c77a9eab0'
down_revision = 'fd7868b5c3bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dinner_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lunch_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.drop_column('lunch_count')
        batch_op.drop_column('dinner_count')

    # ### end Alembic commands ###
