"""updated db

Revision ID: d02cdf535e82
Revises: 857c77a9eab0
Create Date: 2022-11-25 21:28:57.036335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd02cdf535e82'
down_revision = '857c77a9eab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.alter_column('quant',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('meal_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.alter_column('meal_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('quant',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
