"""Initial migration.

Revision ID: fd7868b5c3bc
Revises: 
Create Date: 2022-11-24 12:44:00.886676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7868b5c3bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quant', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=100), nullable=False),
    sa.Column('protein', sa.String(length=100), nullable=True),
    sa.Column('last_ate', sa.String(length=100), nullable=True),
    sa.Column('created', sa.String(length=100), nullable=True),
    sa.Column('child_ok', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal')
    # ### end Alembic commands ###
